### ISSUE TITLE
Demos do not work

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#1711]
### Issue Description

The demos of substrate connect do not work anymore. When trying to run them the following error appears:
```
  ✘ [ERROR] Failed to resolve entry for package "@substrate/connect". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1363:21:
      1363 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28725:11)
    at resolvePackageEntry (file:///Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28722:5)
    at tryNodeResolve (file:///Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28453:20)
    at Context.resolveId (file:///Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:28212:28)
    at Object.resolveId (file:///Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44276:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44581:26)
    at async file:///Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44758:34
    at async requestCallbacks.on-resolve (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:1363:22)
    at async handleRequest (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:726:13)

  This error came from the "onResolve" callback registered here:

    ../../node_modules/vite/node_modules/esbuild/lib/main.js:1282:20:
      1282 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44748:19)
    at handlePlugins (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:1282:21)
    at buildOrContextImpl (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:971:5)
    at Object.buildOrContext (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:779:5)
    at /Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:2175:68
    at new Promise (<anonymous>)
    at Object.context (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:2175:27)
    at Object.context (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:2015:58)
    at prepareEsbuildScanner (file:///Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44531:26)

  The plugin "vite:dep-scan" was triggered by this import

    src/index.ts:7:7:
      7 │ } from "@substrate/connect"
        ╵        ~~~~~~~~~~~~~~~~~~~~


    at failureErrorWithLog (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:1639:15)
    at /Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:1051:25
    at runOnEndCallbacks (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:1474:45)
    at buildResponseToResult (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:1049:7)
    at /Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:1061:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:1060:54)
    at handleRequest (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:726:19)
    at handleIncomingPacket (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:748:7)
    at Socket.readFromStdout (/Users/stormsheep/Documents/repos/parity/ts/substrate-connect/node_modules/vite/node_modules/esbuild/lib/main.js:676:7)
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. from root run `yarn i`
2. Run `yarn run dev:demo`
3.

### Describe the results you received

See issue description above	

### Describe the results you expected

The project should run without any issue 

### Substrate-Connect version

0.8.4

### Provider

Brave

### Browser version

Independent

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by kratico** [comment]
@wirednkod I'm not able to repro this locally with Node v18.

- What Node version are you using?
- Did you run `yarn build` before `yarn run dev:demo`?

BTW, https://paritytech.github.io/substrate-connect/demo/ was successfully deployed and it seems to be working with the new version.

**Comment by wirednkod** [comment]
Step `yarn run build` was missing. 

You should definetly update the documentation in the repo (and note with big bold letters the breaking changes from 0.7 -> 0.8.

Also all documentations [[1](https://paritytech.github.io/substrate-connect/api/), [2](https://docs.substrate.io/learn/light-clients-in-substrate-connect/)] are out of date and they should be updated. I'll open a new issue for that
