### ISSUE TITLE
Fix flickering Detector tests

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#294]
```bash
    ✕ Should connect with known chain westend, no chainSpecs and options (3279 ms)
    ✓ Should connect with known chain "kusama". (7542 ms)
    ✓ Should connect with unknown chain westend2 and chainSpecs. (3228 ms)
    ✓ Should NOT connect with unknown chain westend2 and without chainSpecs. (2 ms)

  ● Initialize Detector without extension › Should connect with known chain westend, no chainSpecs and options

    terminate() has been called

      278 |         if (this.#client) {
      279 |           // eslint-disable-next-line @typescript-eslint/no-unsafe-call
    > 280 |           this.#client.terminate();
          |                        ^
      281 |         }
      282 |       } catch(error: unknown) {
      283 |         this.emit('error', error);

      at Object.terminate (../../node_modules/smoldot/src/index.js:163:23)
      at SmoldotProvider.disconnect (src/SmoldotProvider/SmoldotProvider.ts:280:24)
      at Detector.disconnect (src/Detector.ts:51:38)
      at Object.<anonymous> (src/Detector.test.ts:22:18)
```

This only happens intermittently.

**Comment by wirednkod** [comment]
Since tests have been altered due to API changes, this issue have not appeared again, so this can close
